var http = require('http')
var fs = require ('fs')
var url =  require ('url')
var axios = require ('axios')


function genOcorrencias(ocorrencias){
    pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lista de OcorrÃªncias</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-blue">
              <h1>Lista de OcorrÃªncias</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Data</th>
                        <th>Animal</th>
                      </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.id}</td>
            <td>${ocorr.bite_date}</td>
            <td>${ocorr.SpeciesIDDesc}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}



http.createServer((req,res) => {
	console.log(req.method + " " + req.url);

	if(req.url == '/')
	{
		fs.readFile("web.html", (erro, dados) => 
		{
			res.writeHead(200, {"Content-Type" : "text/html; charset=utf-8"})
			res.write(dados)
			res.end()
		})


	}else if(req.url == '/animais'){
		axios.get("http://localhost:3000/ocorrencias")
		.then(resp => {
			console.log(resp)
			res.writeHead(200, {"Content-Type" : "text/html; charset=utf-8"})
			html = genOcorrencias(resp.data)
			res.write(html)
			res.end()
		})
		.catch(erro => {
			res.writeHead(200, {"Content-Type" : "text/html; charset=utf-8"})
			res.write("<p>Ocorreu um erro:" + erro + "</p>")
			res.end()
		
		})

	}else if(req.url == '/animaisJSON'){
			axios.get("http://localhost:3000/ocorrencias")
			.then(resp => {
				console.log(resp)
				res.writeHead(200, {"Content-Type" : "text/json; charset=utf-8"})
				res.write(JSON.stringify(resp.data))
				res.end()
			})
			.catch(erro => {
				res.writeHead(200, {"Content-Type" : "text/html; charset=utf-8"})
				res.write("<p>Ocorreu um erro:" + erro + "</p>")
				res.end()
			
			})
	}
	else if(req.url == '/w3.css')

	{
		fs.readFile("w3.css", (erro, dados) => {
				res.writeHead(200, {"Content-Type" : "text/css;"})
				res.write(dados)
				res.end()
		})
	}
	else 
	{
			res.writeHead(400, {"Content-Type" : "text/html; charset=utf-8"})
			res.write("<p>Erro: Pedido nao suportado<p>")
			res.write("<pre>" + req.url + "</pre>")
			res.end()
	}


}).listen(2702)

console.log("Servidor à escuta na porta 2702")
